BASE_DIR:
  /home/mileschristiansmith_gmail_com/workspace
SOURCE_DIR:
  /s4
PROJECT_DIR:
  /S4_4
RAW_DATA_DIR:
  /raw_data
OUT_DIR:
  /results
REF_DIR:
  /references
SEQUENCES_DIR:
  /genomic
SPECIES:
  /homo_sapiens
GTF:
  /homo_sapiens/sequences/gencode.v29.annotation.gtf
FASTA:
  /homo_sapiens/sequences/GRCh38.primary_assembly.genome.fa.gz
STAR_INDEX:
  /homo_sapiens/indices/star/gencode_v28_with_virus
KALLISTO_INDEX:
  /homo_sapiens/indices/kallisto/gencode_v29_transcripts.idx
RESOURCE_DIR:
  /miscellaneous
POLY_A:
  /polyA.fa.gz
TRUSEQ_RNA:
  /truseq_rna.fa.gz
TRUSEQ:
  /truseq.fa.gz
RRNAREF:
  /human_ribosomal.fa
GENOME_BUILD:
  hg38
