BASE_DIR:
  memory_alpha
SOURCE_DIR:
  /RNAseq
RAW_DATA_DIR:
  /raw_data
PROJECT_DIR:
  /hyperprep_trial
OUT_DIR:
  /results
REF_DIR:
  /references
SPECIES:
  /homo_sapiens
SEQUENCES_DIR:
  /genomic/sequences
GTF:
  /gencode.v29.annotation.gtf
FASTA:
  /GRCh38.primary_assembly.genome.fa.gz
STAR_INDEX:
  /indices/star/gencode_v28_with_virus
KALLISTO_INDEX:
  /indices/kallisto/gencode_v29_transcripts.idx
RESOURCE_DIR:
  /miscellaneous
POLY_A:
  /polyA.fa.gz
TRUSEQ_RNA:
  /truseq_rna.fa.gz
TRUSEQ:
  /truseq.fa.gz
RRNAREF:
  /human_ribosomal.fa

GENOME_BUILD:
  hg38
