BASE_DIR:
  /s
SOURCE_DIR:
  /guth-aci
PROJECT_DIR:
  /quantseq2
RAW_DATA_DIR:
  /data/raw_data/fastqs
RESULTS_DIR:
  /data/results
LOG_DIR:
  /logs
REF_DIR:
  /Volumes/guth_aci_informatics/references
SEQUENCES_DIR:
  /genomic
SPECIES:
  /homo_sapiens
GTF:
  /homo_sapiens/sequences/Homo_sapiens.GRCh38.97.gtf
FASTA:
  /homo_sapiens/sequences/GRCh38.primary_assembly.genome.fa.gz
STAR_INDEX:
  /homo_sapiens/indices/star/ensembl_GRCh38_97
KALLISTO_INDEX:
  /homo_sapiens/indices/kallisto/gencode_v29_transcripts.idx
RESOURCE_DIR:
  /miscellaneous
POLY_A:
  /polyA.fa.gz
TRUSEQ_RNA:
  /truseq_rna.fa.gz
TRUSEQ:
  /truseq.fa.gz
RRNAREF:
  /human_ribosomal.fa
GENOME_BUILD:
  hg38
