BASE_DIR:
  /s/guth-aci
SOURCE_DIR:
  /novaseq
PROJECT_DIR:
  /S4.2
RAW_DATA_DIR:
  /data/raw_data/fastqs/s42
RESULTS_DIR:
  /data/results
LOG_DIR:
  /logs
REF_DIR:
  /Volumes/guth_aci_informatics/references
SEQUENCES_DIR:
  /genomic
SPECIES:
  /homo_sapiens
GTF:
  /homo_sapiens/sequences/gencode.v32.primary_assembly.annotation.gtf
FASTA:
  /homo_sapiens/sequences/GRCh38.primary_assembly.genome.fa
STAR_INDEX:
  /homo_sapiens/indices/star/gencode_v32
KALLISTO_INDEX:
  /homo_sapiens/indices/kallisto/gencode_v31_transcripts.idx
SALMON_INDEX:
  /homo_sapiens/indices/salmon/gencode_v32
SUBREAD_INDEX:
  /chimeras/indices/subread/
RESOURCE_DIR:
  /miscellaneous
POLY_A:
  /polyA.fa.gz
TRUSEQ_RNA:
  /truseq_rna.fa.gz
TRUSEQ:
  /truseq.fa.gz
RRNAREF:
  /human_ribosomal.fa
GENOME_BUILD:
  hg38
