PROJECT:
  /s/guth-aci/novaseq/dockerized_test
RAW_DATA:
  /data/raw_data/fastqs
RESULTS:
  /data/results
LOGS:
  /logs
REFERENCES:
  /Volumes/guth_aci_informatics/references
GENOMIC_FILES:
  /genomic
SPECIES:
  /homo_sapiens
SEQUENCES:
  /sequences
GTF:
  /gencode.v32.primary_assembly.annotation.gtf
FASTA:
  /GRCh38.primary_assembly.genome.fa
INDICES:
  /indices
STAR_INDEX:
  /star/gencode_v32
SALMON_INDEX:
  /salmon/gencode_v32
SUBREAD_INDEX:
  /chimeras/indices/subread/
RSEM_INDEX:
  /homo_sapiens/indices/rsem/rsem_gencode_v32
MISCELLANEOUS:
  /miscellaneous
POLY_A:
  /polyA.fa.gz
TRUSEQ_RNA:
  /truseq_rna.fa.gz
TRUSEQ:
  /truseq.fa.gz
RRNAREF:
  /human_ribosomal.fa
TRANSCRIPTOME:
  ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_32/gencode.v32.transcripts.fa.gz
GENOME:
  ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_32/GRCh38.primary_assembly.genome.fa.gz